describe('change application', () => {
    it('passes', () => {
        cy.fixture('example').then(data => {
            cy.visit('https://dev.profteam.su/login')
            cy.log('ввод логина')
            cy.get('.form-input--text')
                .type(data.val_login)
            cy.log('ввод пароля')
            cy.get('.form-input--password')
                .type(data.val_password)
            cy.log('кнопка Войти')
            cy.get('.form__buttons > :nth-child(3)')
                .click()
            cy.log('Заявки')
            cy.get(':nth-child(3) > .menu-item__item-name')
                .click()
            cy.log('Ихменить')
            cy.get('.button__background-color-light-blue')
                .click()
            cy.log('Изменить название организации')
            cy.get('.desktop-modal__content > .create-company-form > :nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text')
                .type(data.other_title)
            cy.log('кнопка Добавить')
            cy.get('.desktop-modal__content > .create-company-form > .create-company-form__description-block > .button')
                .click()
        })
    })
})