describe('create commercial application', () => {
    it('passes', () => {
        cy.fixture('example').then(data => {
            cy.visit('https://dev.profteam.su/login')
            cy.log('ввод логина')
            cy.get('.form-input--text')
                .type(data.val_login)
            cy.log('ввод пароля')
            cy.get('.form-input--password')
                .type(data.val_password)
            cy.log('кнопка Войти')
            cy.get('.form__buttons > :nth-child(3)')
                .click()
            cy.log('выбрать роль')
            cy.get('.page-nav__role-block > .button')
                .click()
            cy.log('Выбор роли')
            cy.get('.select-role-form > :nth-child(1)')
                .click()
            cy.get('.variants-company > :nth-child(1)')
                .click()
            cy.log('выбор компании')
            cy.get('div.search-input__field > .form-input--text')
                .type(data.commercial_organization)
            cy.get('.search-input__item')
                .click()
            cy.log('кнопка Выбрать компанию')
            cy.get('.choose-company > .button')
                .click()
        })
    })
})