describe('create office', () => {
    it('passes', () => {
        cy.fixture('example').then(data => {
            cy.visit('https://dev.profteam.su/login')
            cy.log('ввод логина')
            cy.get('.form-input--text')
                .type(data.val_login)
            cy.log('ввод пароля')
            cy.get('.form-input--password')
                .type(data.val_password)
            cy.log('кнопка Войти')
            cy.get('.form__buttons > :nth-child(3)')
                .click()
            cy.log('выбрать роль')
            cy.get('.page-nav__role-block > .button')
                .click()
            cy.log('Выбор роли')
            cy.get('.select-role-form > :nth-child(2)')
                .click()
            cy.get('.variants-company > :nth-child(2)')
                .click()
            cy.log('Ввод названия организации')
            cy.get(':nth-child(1) > .form-control--medium > .form-input--text')
                .type(data.new_organization)
            cy.log('Ввод адреса')
            cy.get(':nth-child(2) > .form-control--medium > .form-input--text')
                .type(data.address)
            cy.log('краткое описание')
            cy.get('.form-area')
                .type(data.description)
            cy.log('кнопка Добавить')
            cy.get('.create-company-form__description-block > .button')
                .click()
        })
    })
})