describe('error verification', () => {
    it('passes', () => {
        cy.fixture('example').then(data => {
            cy.visit('https://dev.profteam.su/login')
            cy.log('ввод логина')
            cy.get('.form-input--text')
                .type(data.val_login)
            cy.log('ввод пароля')
            cy.get('.form-input--password')
                .type(data.val_password)
            cy.log('кнопка Войти')
            cy.get('.form__buttons > :nth-child(3)')
                .click()
            cy.log('кнопка Выбрать роль')
            cy.get('.page-nav__role-block > .button')
                .click()
            cy.log('Выбор роли')
            cy.get('.select-role-form > :nth-child(3)')
                .click()
            cy.log('кнопка Пройти верификацию')
            cy.get('.message-student > .button')
                .click()
            cy.log('Ввод образовательного учреждени')
            cy.get('.desktop-modal__content > .student-form > .choose-institution > :nth-child(1) > [data-v-40f88df4=""] > .search-input > div.search-input__field > .form-input--text')
                .type(data.organization)
            cy.wait(1000)
            cy.get('.search-input__item')
                .click()
            cy.log('Выбор специальности')
            cy.get('.desktop-modal__content > .student-form > .choose-specialty > [data-v-0dbb9e5f=""] > .search-input > div.search-input__field > .form-input--text')
                .type(data.specialization)
            cy.wait(1000)
            cy.get('.search-input__item')
                .click()
            cy.log('выбор квалификации')
            cy.get('.desktop-modal__content > .student-form > :nth-child(3) > .form-control--max > .form-input--text')
                .type(data.qualification)

            cy.log('выбор курса')
            cy.get('.desktop-modal__content > .student-form > .student-form__courses > .courses-list > :nth-child(2)')
                .click()
            cy.log('Ввод неправильного года')
            cy.get('.desktop-modal__content > .student-form > .student-form__years > :nth-child(1) > .form-control--max > .form-input--number')
                .type(data.error_start_education)
            cy.log('Ввод неправильного года')
            cy.get('.desktop-modal__content > .student-form > .student-form__years > :nth-child(2) > .form-control--max > .form-input--number')
                .type(data.error_finish_education)
            cy.log('Проверка на ошибку')
            cy.get('.form-error > span')
                .should('exist')
        })
    })
})