describe('registration tests', () => {
    it('passes', () => {
        cy.fixture('example').then(data => {
            cy.visit('https://dev.profteam.su/registration')
            cy.log('ввод логина')
            cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text')
                .type(data.val_login)
            cy.log('ввод электронной почты')
            cy.get('.form-input--email')
                .type(data.val_email)
            cy.log('ввод пароля')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--password')
                .type(data.val_password)
            cy.log('повтор ввода пароля')
            cy.get(':nth-child(4) > .form-control--medium > .form-input--password')
                .type(data.val_password)
            cy.log('кнопака Войти')
            cy.get(':nth-child(4) > .button')
                .click()
            cy.log('Ввод фамилии')
            cy.get('[style=""] > :nth-child(1) > .form-control--medium > .form-input--text')
                .type(data.surname)
            cy.log('Ввод имени')
            cy.get(':nth-child(2) > .form-control--medium > .form-input--text')
                .type(data.name)
            cy.log('Ввод отчества')
            cy.get(':nth-child(3) > .form-control--medium > .form-input--text')
                .type(data.patronymic)
            cy.log('кнопка Создать аккаунт')
            cy.get('.form__buttons > :nth-child(3)')
                .click()
        })
    })

    // it('passes', () => {
    //     cy.fixture('example').then(data => {
    //         cy.visit('https://dev.profteam.su/registration')
    //         cy.log('ввод логина')
    //         cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text')
    //             .type(data.login)
    //         cy.log('ввод электронной почты, которая уже используется')
    //         cy.get('.form-input--email')
    //             .type(data.val_email)
    //         cy.log('ввод пароля')
    //         cy.get(':nth-child(3) > .form-control--medium > .form-input--password')
    //             .type(data.val_password)
    //         cy.log('повтор ввода пароля')
    //         cy.get(':nth-child(4) > .form-control--medium > .form-input--password')
    //             .type(data.val_password)
    //         cy.log('кнопака Войти')
    //         cy.get(':nth-child(4) > .button')
    //             .click()
    //         cy.log('Проверка на ошибку')
    //         cy.get('.form-error > span')
    //             .should('exist')
    //     })
    // })
    // it('passes', () => {
    //     cy.fixture('example').then(data => {
    //         cy.visit('https://dev.profteam.su/registration')
    //         cy.log('ввод существующего логина')
    //         cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text')
    //             .type(data.val_login)
    //         cy.log('ввод электронной почты')
    //         cy.get('.form-input--email')
    //             .type(data.not_exist_email)
    //         cy.log('ввод пароля')
    //         cy.get(':nth-child(3) > .form-control--medium > .form-input--password')
    //             .type(data.not_exist_password)
    //         cy.log('повтор ввода пароля')
    //         cy.get(':nth-child(4) > .form-control--medium > .form-input--password')
    //             .type(data.not_exist_password)
    //         cy.log('кнопака Войти')
    //         cy.get(':nth-child(4) > .button')
    //             .click()
    //         cy.log('Проверка на ошибку')
    //         cy.get('.form-error > span')
    //             .should('exist')
    //     })
    // })

    // it('passes', () => {
    //     cy.fixture('example').then(data => {
    //         cy.visit('https://dev.profteam.su/registration')
    //         cy.log('ввод логина на русском языке')
    //         cy.get(':nth-child(1) > :nth-child(1) > .form-control--medium > .form-input--text')
    //             .type(data.enter_login_rus)
    //         cy.log('ввод электронной почты')
    //         cy.get('.form-input--email')
    //             .type(data.not_exist_email)
    //         cy.log('ввод пароля')
    //         cy.get(':nth-child(3) > .form-control--medium > .form-input--password')
    //             .type(data.not_exist_password)
    //         cy.log('повтор ввода пароля')
    //         cy.get(':nth-child(4) > .form-control--medium > .form-input--password')
    //             .type(data.not_exist_password)
    //         cy.log('Проверка на ошибку')
    //         cy.get('.form-error > span')
    //             .should('exist')
    //     })
    // })
})